app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: master
finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --filesystem=/etc/dconf/db/gdm.d
  - --filesystem=/etc/dconf/profile/gdm
  - --filesystem=/usr/share/gnome-shell/gnome-shell-theme.gresource
  - --filesystem=/usr/share/gnome-shell/gnome-shell-theme.gresource.default
cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
modules:
  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: dir
        path: '.'
