app-id: io.github.realmazharhussain.GdmSettings
runtime: org.gnome.Sdk
runtime-version: master
sdk: org.gnome.Platform
command: gdm-settings
finish-args:
  - --share=network
  - --share=ipc
  - --socket=fallback-x11
  - --device=dri
  - --socket=wayland
cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
modules:
  - name: gdm-settings
    builddir: true
    buildsystem: meson
    sources:
      - type: dir
        path: '.'
