app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "42"
finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=host-os
  - --filesystem=host-etc
cleanup:
  - /bin/blueprint-compiler
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
modules:
  - name: gdm-settings
    builddir: true
    buildsystem: meson
    config-opts:
      - --buildtype=release
    sources:
      - type: dir
        path: '.'
